robot_names = ["Extreme Network Defense Machine",
"Nuclear War Domination Bot",
"Independent Pilot Bot",
"Motorized Inspection Golem",
"Plier",
"Qwerty",
"Scrap",
"Brobot",
"Oha",
"Uyu",
"Dynamic War Robot",
"Extreme Troubleshooting Emulator",
"Humanoid Observer Machine",
"Sensitive Shepherd Device",
"Tech",
"Mace",
"Sark",
"Norbit",
"Exix",
"Awov",
"Global Personal Protection Robot",
"Self-Regulaing Pilot Prototype",
"Sensory Air Safety Android",
"Artificial Robot Control Emulator",
"Rob Bott",
"Micro",
"Crowby",
"Mace",
"Ug",
"Ere",
"Sensitive Education Robot",
"Cybernated Mapping Android",
"Unified Supervision Cyborg",
"Exceptional Peacekeeping Golem",
"Knave",
"Earl",
"Andy Roid",
"Data",
"Eqen",
"Oj"
]